# Generated by Django 5.2.6 on 2025-09-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenha',
            name='user_id',
        ),
    ]
