# Generated by Django 5.2.6 on 2025-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_resenha_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resenhas_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='usuarios', to='app.resenha'),
        ),
    ]
