# Generated by Django 5.2.6 on 2025-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_resenhas_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resenhas_ids',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='app.resenha'),
        ),
    ]
