# Generated by Django 5.2.6 on 2025-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_resenhas_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
